version: 2.1

orbs:
  queue: eddiewebb/queue@1.8.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - queue/until_front_of_line:
          only-on-branch: main
          time: '10'
      - checkout
      - run:
          name: Snooze time
          command: sleep 100

workflows:
  my-workflow:
    jobs:
      - build:
          context:
            - cci