version: 2.1

orbs:
  queue: eddiewebb/queue@2.2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Snooze time
          command: sleep 60

workflows:
  my-workflow:
    jobs:
      - queue/block_workflow:
          only-on-branch: main
          time: '10'
          block-workflow: false
          context:
            - cci
      - build:
          requires:
            - queue/block_workflow